<div id="wikiView" >
<p>William Henry "Bill" Gates III, (born October 28, 1955)[2] is an American business magnate, philanthropist, author and was chairman[3] of Microsoft until 2008, the software company he founded with Paul Allen. He is consistently ranked among the world's wealthiest people[4] and was the wealthiest overall from 1995 to 2009, excluding 2008, when he was ranked third.[5] During his career at Microsoft, Gates held the positions of CEO and chief software architect, and remains the largest individual shareholder with more than 8 percent of the common stock.[6] He has also authored or co-authored several books.

<p>Gates is one of the best-known entrepreneurs of the personal computer revolution. Although he is admired by many, a number of industry insiders criticize his business tactics, which they consider anti-competitive, an opinion which has in some cases been upheld by the courts.[7][8] In the later stages of his career, Gates has pursued a number of philanthropic endeavors, donating large amounts of money to various charitable organizations and scientific research programs through the Bill & Melinda Gates Foundation, established in 2000.

<p>Bill Gates stepped down as chief executive officer of Microsoft in January 2000. He remained as chairman and created the position of chief software architect. In June 2006, Gates announced that he would be transitioning from full-time work at Microsoft to part-time work and full-time work at the Bill & Melinda Gates Foundation. He gradually transferred his duties to Ray Ozzie, chief software architect and Craig Mundie, chief research and strategy officer. Gates' last full-time day at Microsoft was June 27, 2008. He remains at Microsoft as non-executive chairman.
↑ Jump Back A Section
ShowHide Early life

<p>Gates was born in Seattle, Washington, to William H. Gates, Sr. and Mary Maxwell Gates, of English, German, and Scotch-Irish descent.[9][10] His family was upper middle class; his father was a prominent lawyer, his mother served on the board of directors for First Interstate BancSystem and the United Way, and her father, J. W. Maxwell, was a national bank president. Gates has one elder sister, Kristi (Kristianne), and one younger sister, Libby. He was the fourth of his name in his family, but was known as William Gates III or "Trey" because his father had dropped his own "III" suffix.[11] Early on in his life, Gates' parents had a law career in mind for him.[12]

<p>At 13 he enrolled in the Lakeside School, an exclusive preparatory school.[13] When he was in the eighth grade, the Mothers Club at the school used proceeds from Lakeside School's rummage sale to buy an ASR-33 teletype terminal and a block of computer time on a General Electric (GE) computer for the school's students.[14] Gates took an interest in programming the GE system in BASIC and was excused from math classes to pursue his interest. He wrote his first computer program on this machine: an implementation of tic-tac-toe that allowed users to play games against the computer. Gates was fascinated by the machine and how it would always execute software code perfectly. When he reflected back on that moment, he commented on it and said, "There was just something neat about the machine."[15] After the Mothers Club donation was exhausted, he and other students sought time on systems including DEC PDP minicomputers. One of these systems was a PDP-10 belonging to Computer Center Corporation (CCC), which banned four Lakeside students—Gates, Paul Allen, Ric Weiland, and Kent Evans—for the summer after it caught them exploiting bugs in the operating system to obtain free computer time.[16]

<p>At the end of the ban, the four students offered to find bugs in CCC's software in exchange for computer time. Rather than use the system via teletype, Gates went to CCC's offices and studied source code for various programs that ran on the system, including programs in FORTRAN, LISP, and machine language. The arrangement with CCC continued until 1970, when the company went out of business. The following year, Information Sciences, Inc. hired the four Lakeside students to write a payroll program in COBOL, providing them computer time and royalties. After his administrators became aware of his programming abilities, Gates wrote the school's computer program to schedule students in classes. He modified the code so that he was placed in classes with mostly female students. He later stated that "it was hard to tear myself away from a machine at which I could so unambiguously demonstrate success."[15] At age 17, Gates formed a venture with Allen, called Traf-O-Data, to make traffic counters based on the Intel 8008 processor.[17] In early 1973, Bill Gates served as a congressional page in the U.S. House of Representatives.[18]

<p>Gates graduated from Lakeside School in 1973. He scored 1590 out of 1600 on the SAT[19] and enrolled at Harvard College in the autumn of 1973.[20] While at Harvard, he met Steve Ballmer, who later succeeded Gates as CEO of Microsoft.

<p>In his sophomore year, Gates devised an algorithm for pancake sorting as a solution to one of a series of unsolved problems[21] presented in a combinatorics class by Harry Lewis, one of his professors. Gates' solution held the record as the fastest version for over thirty years;[21][22] its successor is faster by only one percent.[21] His solution was later formalized in a published paper in collaboration with Harvard computer scientist Christos Papadimitriou.[23]

<p>Gates did not have a definite study plan while a student at Harvard[24] and spent a lot of time using the school's computers. He remained in contact with Paul Allen, joining him at Honeywell during the summer of 1974.[25] The following year saw the release of the MITS Altair 8800 based on the Intel 8080 CPU, and Gates and Allen saw this as the opportunity to start their own computer software company.[26] He had talked this decision over with his parents, who were supportive of him after seeing how much Gates wanted to start a company.[24]
↑ Jump Back A Section
ShowHide Microsoft
Main articles: History of Microsoft and Microsoft
BASIC
MITS Altair 8800 Computer with 8-inch (200 mm) floppy disk system

<p>After reading the January 1975 issue of Popular Electronics that demonstrated the Altair 8800, Gates contacted Micro Instrumentation and Telemetry Systems (MITS), the creators of the new microcomputer, to inform them that he and others were working on a BASIC interpreter for the platform.[27] In reality, Gates and Allen did not have an Altair and had not written code for it; they merely wanted to gauge MITS's interest. MITS president Ed Roberts agreed to meet them for a demo, and over the course of a few weeks they developed an Altair emulator that ran on a minicomputer, and then the BASIC interpreter. The demonstration, held at MITS's offices in Albuquerque, was a success and resulted in a deal with MITS to distribute the interpreter as Altair BASIC. Paul Allen was hired into MITS,[28] and Gates took a leave of absence from Harvard to work with Allen at MITS in Albuquerque in November 1975. They named their partnership "Micro-Soft" and had their first office located in Albuquerque.[28] Within a year, the hyphen was dropped, and on November 26, 1976, the trade name "Microsoft" was registered with the Office of the Secretary of the State of New Mexico.[28] Gates never returned to Harvard to complete his studies.

<p>Microsoft's BASIC was popular with computer hobbyists, but Gates discovered that a pre-market copy had leaked into the community and was being widely copied and distributed. In February 1976, Gates wrote an Open Letter to Hobbyists in the MITS newsletter saying that MITS could not continue to produce, distribute, and maintain high-quality software without payment.[29] This letter was unpopular with many computer hobbyists, but Gates persisted in his belief that software developers should be able to demand payment. Microsoft became independent of MITS in late 1976, and it continued to develop programming language software for various systems.[28] The company moved from Albuquerque to its new home in Bellevue, Washington on January 1, 1979.[27]

<p>During Microsoft's early years, all employees had broad responsibility for the company's business. Gates oversaw the business details, but continued to write code as well. In the first five years, he personally reviewed every line of code the company shipped, and often rewrote parts of it as he saw fit.[30]
IBM partnership

<p>In 1980, IBM approached Microsoft to write the BASIC interpreter for its upcoming personal computer, the IBM PC. When IBM's representatives mentioned that they needed an operating system, Gates referred them to Digital Research (DRI), makers of the widely used CP/M operating system.[31] IBM's discussions with Digital Research went poorly, and they did not reach a licensing agreement. IBM representative Jack Sams mentioned the licensing difficulties during a subsequent meeting with Gates and told him to get an acceptable operating system. A few weeks later Gates proposed using 86-DOS (QDOS), an operating system similar to CP/M that Tim Paterson of Seattle Computer Products (SCP) had made for hardware similar to the PC. Microsoft made a deal with SCP to become the exclusive licensing agent, and later the full owner, of 86-DOS. After adapting the operating system for the PC, Microsoft delivered it to IBM as PC-DOS in exchange for a one-time fee of $50,000. Gates did not offer to transfer the copyright on the operating system, because he believed that other hardware vendors would clone IBM's system.[32] They did, and the sales of MS-DOS made Microsoft a major player in the industry.[33]

<p>Gates oversaw Microsoft's company restructuring on June 25, 1981, which re-incorporated the company in Washington state and made Gates President of Microsoft and the Chairman of the Board.[27]
Windows

<p>Microsoft launched its first retail version of Microsoft Windows on November 20, 1985, and in August, the company struck a deal with IBM to develop a separate operating system called OS/2. Although the two companies successfully developed the first version of the new system, mounting creative differences undermined the partnership. Gates distributed an internal memo on May 16, 1991, announcing that the OS/2 partnership was over and Microsoft would shift its efforts to the Windows NT kernel development.[34]
Management style

<p>From Microsoft's founding in 1975 until 2006, Gates had primary responsibility for the company's product strategy. He aggressively broadened the company's range of products, and wherever Microsoft achieved a dominant position he vigorously defended it.

<p>As an executive, Gates met regularly with Microsoft's senior managers and program managers. Firsthand accounts of these meetings describe him as verbally combative, berating managers for perceived holes in their business strategies or proposals that placed the company's long-term interests at risk.[35][36] He often interrupted presentations with such comments as, "That's the stupidest thing I've ever heard!"[37] and, "Why don't you just give up your options and join the Peace Corps?"[38] The target of his outburst then had to defend the proposal in detail until, hopefully, Gates was fully convinced.[37] When subordinates appeared to be procrastinating, he was known to remark sarcastically, "I'll do it over the weekend."[3][39][40]

<p>Gates's role at Microsoft for most of its history was primarily a management and executive role. However, he was an active software developer in the early years, particularly on the company's programming language products. He has not officially been on a development team since working on the TRS-80 Model 100 line, but wrote code as late as 1989 that shipped in the company's products.[39] On June 15, 2006, Gates announced that he would transition out of his day-to-day role over the next two years to dedicate more time to philanthropy. He divided his responsibilities between two successors, placing Ray Ozzie in charge of day-to-day management and Craig Mundie in charge of long-term product strategy.[41]
Antitrust litigation
Further information: United States Microsoft antitrust case and European Union Microsoft competition case
Bill Gates giving his deposition at Microsoft on August 27, 1998

<p>Many decisions that led to antitrust litigation over Microsoft's business practices have had Gates' approval. In the 1998 United States v. Microsoft case, Gates gave deposition testimony that several journalists characterized as evasive. He argued with examiner David Boies over the contextual meaning of words like "compete", "concerned" and "we".[42] BusinessWeek reported:

<p>blah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balhblah blah blah balh</p>
</div>